#!/usr/bin/env python

from libs.cli import CLIArguments
import os
import importlib


def load_class(full_class_string):
    """
    dynamically load a class from a string
    """

    class_data = full_class_string.split(".")
    module_path = ".".join(class_data[:-1])
    class_str = class_data[-1]

    module = importlib.import_module(module_path)
    # Finally, we retrieve the Class
    return getattr(module, class_str)


if __name__ == '__main__':
    cli = CLIArguments(
            os.path.dirname(os.path.realpath(__file__))
            )
    cli.run()

    cli.args.__dict__['program_path'] = cli.program_path
    module = load_class(cli.getModulePath())
    module(
            **cli.args.__dict__
            ).run()
